### ISSUE TITLE
Chapter8 Encodings JSON field tags

### ISSUE THREAD

**Issue by graugans** [juanmanuel-tirado/savetheworldwithgo#6]
Hey, thanks for writing such a great book. Coming from a C++ background I found it very helpful and providing exactly the level of information I was searching for as a starting point.

One thing which I did not understand without searching the web was your example 8.5 `Custom struct JSON marshalling` In the text:

> This happens because the field visibility does not allow exporting values. 

I rechecket the Chapter about structs but could not find anything about field visibility. So maybe you could provide more details in both the part where you explain the concept of structs and when it comes to the marshalling to JSON part. This may help other readers coming from a language where the first letter of a member does not change its visibility.

**Comment by juanmanuel-tirado** [comment]
You're right. The next revision of the book comes with an extended explanation about variables and functions visibility.

Thanks for the comment. I really appreciate it.
